_wandb:
    value:
        cli_version: 0.25.0
        e:
            7vw75gy5e3gw1k6xobg54gmpkpiq2z63:
                args:
                    - -d
                    - mnist
                    - -e
                    - "30"
                    - -b
                    - "32"
                    - -l
                    - cross_entropy
                    - -o
                    - rmsprop
                    - -lr
                    - "0.001"
                    - -wd
                    - "0.0005"
                    - -nhl
                    - "3"
                    - -sz
                    - "128"
                    - "64"
                    - "32"
                    - -a
                    - relu
                    - -w_i
                    - xavier
                    - -w_p
                    - mnist_sweep
                codePath: src\train.py
                codePathLocal: src\train.py
                cpu_count: 8
                cpu_count_logical: 12
                disk:
                    /:
                        total: "258063986688"
                        used: "223299764224"
                email: ic43581@imail.iitm.ac.in
                executable: C:\Program Files\Python313\python.exe
                git:
                    commit: 6fc30ccf2999e2bae0999711c857542a49d8af17
                    remote: https://github.com/Nandhini30-cmd/MLP_assignment.git
                host: Nandhini-M
                memory:
                    total: "16857817088"
                os: Windows-11-10.0.26200-SP0
                program: C:\Users\Nandhini\Downloads\da6401_assignment_1-main\da6401_assignment_1-main\src\train.py
                python: CPython 3.13.9
                root: C:\Users\Nandhini\Downloads\da6401_assignment_1-main\da6401_assignment_1-main
                startedAt: "2026-03-08T09:22:00.256095Z"
                writerId: 7vw75gy5e3gw1k6xobg54gmpkpiq2z63
        m: []
        python_version: 3.13.9
        t:
            "1":
                - 2
                - 3
                - 5
                - 49
                - 53
            "2":
                - 2
                - 3
                - 5
                - 49
                - 53
            "3":
                - 16
            "4": 3.13.9
            "5": 0.25.0
            "8":
                - 3
            "12": 0.25.0
            "13": windows-amd64
activation:
    value: relu
batch_size:
    value: 32
dataset:
    value: mnist
epochs:
    value: 30
hidden_size:
    value:
        - 128
        - 64
        - 32
learning_rate:
    value: 0.001
loss:
    value: cross_entropy
model_save_path:
    value: null
num_layers:
    value: 3
optimizer:
    value: rmsprop
wandb_project:
    value: mnist_sweep
weight_decay:
    value: 0.0005
weight_init:
    value: xavier
